### PR TITLE
Add Generic and NFData instances

### PR DESCRIPTION
**Pull request by ruhatch**

### CODE REVIEW

**Review by intricate — APPROVED** [review]
LGTM :+1:

**Comment by joelwilliamson** [comment]
It looks like this doesn't work on GHC <=7.4. I'll consider dropping support for older compilers, but I'm not sure what the usage stats are like.

**Comment by joelwilliamson** [comment]
I've also fixed the CI build. Can you rebase onto the latest master?

**Comment by ruhatch** [comment]
Looks like we might be able to get more support by conditionally including `ghc-prim` in the cabal file - I'm happy to try! Do you prefer to support more versions or keep the cabal file cleaner?

**Comment by ruhatch** [comment]
I tried to add an orphan instance to support 7.2.2, but there was no Generic instance for Map to use. I have instead removed support for 7.2.2 and below in the travis config.

**Comment by ruhatch** [comment]
@joelwilliamson do you think this okay to merge?

**Comment by joelwilliamson** [comment]
Yeah. I'll merge it this evening.

**Comment by ruhatch** [comment]
@joelwilliamson sorry to bother you, but could we get this merged? I'd like to point a downstream repo at your master branch :)

**Comment by intricate** [comment]
Thanks @joelwilliamson

**Pull request merged**
